# Generated by Django 5.0 on 2023-12-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_stat',
            field=models.CharField(choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='ordered', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_stat',
            field=models.BooleanField(default=False),
        ),
    ]
