# Generated by Django 5.0 on 2023-12-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_rename_total_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_stat',
            field=models.CharField(choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='shipped', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
