# Generated by Django 5.0 on 2023-12-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_alter_orderitem_delivery_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
