# Generated by Django 5.0 on 2023-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dummy',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
