# Generated by Django 5.0 on 2023-12-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cartitem_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='dummy',
        ),
    ]
